name: Build Ansible EE
on:
  workflow_run:
    workflows: ["Publish to Ansible Galaxy"]
    types:
      - completed

env:
  IMAGE_URI: ghcr.io/${{ github.repository_owner }}/ansible/komodo-ee

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ee-builder
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Wait
        run: sleep 30

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install ansible-builder
        run: python -m pip install --upgrade pip ansible-builder==3.*

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          ansible-builder build \
          --container-runtime docker \
          --tag $IMAGE_URI:latest

      - name: Push latest
        run: docker push $IMAGE_URI:latest

      - name: Push release
        if: startsWith(github.event.workflow_run.head_branch, 'v')
        env:
          TAG_NAME: ${{ github.event.workflow_run.head_branch }}
        run: |
          docker tag $IMAGE_URI:latest $IMAGE_URI:$TAG_NAME
          docker push $IMAGE_URI:$TAG_NAME
